name: 'patient_etl_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'patient_etl_profile' # We will define this profile in profiles.yml

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"] # Though we are not creating analyses in this plan
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"] # Though we are not creating snapshots in this plan

target-path: "target"  # directory for compiled artifacts
clean-targets:         # directories removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models under the "marts" directory to be materialized as tables by default.
# Staging models will be views by default unless specified otherwise.
models:
  patient_etl_analytics: # This is the project name
    # Define model configurations.
    # We can configure specific subdirectories.
    staging:
      +materialized: view # Default for staging models
      # You can add schemas here like: +schema: staging
    marts:
      +materialized: table # Default for mart models
      # You can add schemas here like: +schema: analytics
